name: Deploy via FTPS

on:
  push:
    branches:
      - prod

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List root dir
        run: ls -la
      - name: Deploy to FTP
        uses: samkirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ijen.iixcp.rumahweb.net
          username: ${{ secrets.FTP_USERNAME_ALADIL }}
          password: ${{ secrets.FTP_PASSWORD_ALADIL }}
          port: 21
          protocol: ftps
          server-dir: public_html/tv.masjidaladil.com/
          exclude: |
            .git
            .git/**
            .github
            .github/**
            db/**
            display/logo/**
